---
services:
  weaviate:
    command:
      - --host
      - 0.0.0.0
      - --port
      - "8080"
      - --scheme
      - http
    image: cr.weaviate.io/semitechnologies/weaviate:1.34.0
    ports:
      - 8080:8080
    volumes:
      - weaviate_data:/var/lib/weaviate
    restart: always
    environment:
      QUERY_DEFAULTS_LIMIT: 25
      PERSISTENCE_DATA_PATH: "/var/lib/weaviate"
      ENABLE_MODULES: "text2vec-transformers"
      CLUSTER_HOSTNAME: "node1"
      TRANSFORMERS_INFERENCE_API: http://text2vec-transformers:8080
      TRANSFORMERS_IN_PROCESS: "true"
      # Disable anonymous access.
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: "true"
      # Enables API key authentication.
      AUTHENTICATION_APIKEY_ENABLED: "true"
      # List one or more keys in plaintext separated by commas. Each key corresponds to a specific user identity below.
      AUTHENTICATION_APIKEY_ALLOWED_KEYS: "homeassistant"
      # List one or more user identities, separated by commas. Each identity corresponds to a specific key above.
      AUTHENTICATION_APIKEY_USERS: "homeassistant"

  text2vec-transformers:
    image: cr.weaviate.io/semitechnologies/transformers-inference:sentence-transformers-paraphrase-multilingual-MiniLM-L12-v2
    environment:
      ENABLE_CUDA: "0"

volumes:
  weaviate_data:
